[lib]
proc-macro = true

[package]
name = "compute-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
compute = { path = "../compute" }
logger = { path = "../logger" }

syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
